name = "ens-faucet"
main = "src/index.ts"
compatibility_date = "2023-02-01"
node_compat = true

kv_namespaces = [
  { binding = "USED_ADDRESS_KV", id = "3e72a02e4d714b54b461adc1d529358d", preview_id = "c26e19a6e45a4ee698c513bbebd93f21" }
]

[vars]